name: Sync Fork

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Add remote upstream
      run: git remote add upstream https://github.com/Dadoum/anisette-v3-server.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/main --no-edit

    - name: Push changes
      run: git push
